import = [
  "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
  # "~/.config/alacritty/themes/themes/ayu_dark.toml"
  # "~/.config/alacritty/themes/themes/tokyo-night.toml"
  
]

[font]
size = 13.0
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Regular" } 

[colors.primary]
# background = "#0b0b11"

[colors.normal]
# blue = "#56bdf9"

[window]
option_as_alt = "Both"
