-- vim.keymap.set(
--   "n",
--   "<leader>jeo",
--   ":MoltenEvaluateOperator<CR>",
--   { desc = "evaluate operator", silent = true }
-- )
-- vim.keymap.set(
--   "n",
--   "<leader>jo",
--   ":noautocmd MoltenEnterOutput<CR>",
--   { desc = "open output window", silent = true }
-- )
--
-- vim.keymap.set(
--   "n",
--   "<leader>jec",
--   ":MoltenReevaluateCell<CR>",
--   { desc = "re-eval cell", silent = true }
-- )
-- vim.keymap.set(
--   "v",
--   "<leader>jev",
--   ":<C-u>MoltenEvaluateVisual<CR>gv",
--   { desc = "execute visual selection", silent = true }
-- )
-- vim.keymap.set(
--   "n",
--   "<leader>jho",
--   ":MoltenHideOutput<CR>",
--   { desc = "close output window", silent = true }
-- )
-- vim.keymap.set(
--   "n",
--   "<leader>jdc",
--   ":MoltenDelete<CR>",
--   { desc = "delete Molten cell", silent = true }
-- )
--
-- local runner = require("quarto.runner")
-- vim.keymap.set(
--   "n",
--   "<leader>jrc",
--   runner.run_cell,
--   { desc = "run cell", silent = true }
-- )
-- vim.keymap.set(
--   "n",
--   "<leader>jra",
--   runner.run_above,
--   { desc = "run cell and above", silent = true }
-- )
-- vim.keymap.set(
--   "n",
--   "<leader>jrA",
--   runner.run_all,
--   { desc = "run all cells", silent = true }
-- )
-- vim.keymap.set(
--   "n",
--   "<leader>jrl",
--   runner.run_line,
--   { desc = "run line", silent = true }
-- )
-- vim.keymap.set(
--   "v",
--   "<leader>jrv",
--   runner.run_range,
--   { desc = "run visual range", silent = true }
-- )
-- vim.keymap.set("n", "<leader>jR", function()
--   runner.run_all(true)
-- end, { desc = "run all cells of all languages", silent = true })
