local telescope = require("telescope.builtin")

vim.keymap.set("n", "<M-left>", "<C-w>h")
vim.keymap.set("n", "<M-right>", "<C-w>l")
vim.keymap.set("n", "<M-up>", "<C-w>k")
vim.keymap.set("n", "<M-down>", "<C-w>j")

vim.keymap.set("n", "<leader>bn", "<cmd>bn<CR>")
vim.keymap.set("n", "<leader>bp", "<cmd>bp<CR>")
vim.keymap.set("n", "<leader>bc", "<cmd>enew \\| bd#<CR>")
vim.keymap.set("n", "<leader>bx", "<cmd>bd!<CR>")
-- vim.keymap.set("n", "<leader>bc", ":bd<CR>")
-- vim.keymap.set("n", "<leader>ba", ":vnew<CR>")
vim.keymap.set("n", "<leader>ba", "<cmd>vsplit<CR>")
vim.keymap.set("n", "<leader>bA", "<cmd>split<CR>")
vim.keymap.set("n", "<leader>bl", telescope.buffers, {})
vim.keymap.set("n", "<leader>b<Left>", "<C-w>H", {})
vim.keymap.set("n", "<leader>b<Right>", "<C-w>L", {})
vim.keymap.set("n", "<leader>b<Up>", "<C-w>K", {})
vim.keymap.set("n", "<leader>b<Down>", "<C-w>J", {})

vim.keymap.set("n", "<leader>tn", "<cmd>tabn<CR>", { noremap = true })
vim.keymap.set("n", "<leader>tp", "<cmd>tabp<CR>", { noremap = true })
vim.keymap.set("n", "<leader>tc", "<cmd>tabclose<CR>", { noremap = true })
vim.keymap.set("n", "<leader>ta", "<cmd>tabnew<CR>", { noremap = true })
vim.keymap.set("n", "<leader>to", "<cmd>tabonly<CR>", { noremap = true })
vim.keymap.set("n", "<leader>tmp", "<cmd>-tabmove<CR>", { noremap = true })
vim.keymap.set("n", "<leader>tmn", "<cmd>+tabmove<CR>", { noremap = true })
vim.keymap.set("n", "<leader>t<Left>", "<cmd>tabp<CR>", { noremap = true })
vim.keymap.set("n", "<leader>t<right>", "<cmd>tabn<CR>", { noremap = true })
