require("configs.colorscheme")
require("configs.snippets")
require("configs.diagnostics")
require("configs.opts")
require("configs.autocommands")
require("configs.copilot")
require("configs.command-and-grep")
require("configs.annoyance-fixes")
