# Colors (Ayu Dark)

# Default colors
[colors.primary]
# background = '#0A0E14'
background = "#0b0b11"
foreground = '#B3B1AD'



# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
# blue    = '#53BDFA'
blue = "#56bdf9"
magenta = '#AD6FF7'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#d2a6ff'
cyan    = '#95E6CB'
white   = '#FFFFFF'


# # Colors (Ayu Dark)
#
# # Default colors
# [colors.primary]
# background = '#0A0E14'
# foreground = '#B3B1AD'
#
# # Normal colors
# [colors.normal]
# black   = '#01060E'
# red     = '#EA6C73'
# green   = '#91B362'
# yellow  = '#F9AF4F'
# blue    = '#53BDFA'
# magenta = '#FAE994'
# cyan    = '#90E1C6'
# white   = '#C7C7C7'
#
# # Bright colors
# [colors.bright]
# black   = '#686868'
# red     = '#F07178'
# green   = '#C2D94C'
# yellow  = '#FFB454'
# blue    = '#59C2FF'
# magenta = '#FFEE99'
# cyan    = '#95E6CB'
# white   = '#FFFFFF'
#
